name: CI tests

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python: [ "3.12" ]

    steps:
      - uses: actions/checkout@v4
      - name: Load .env file
        uses: xom9ikk/dotenv@v2
        with:
          path: .
          mode: test
      - name: Setup python ${{ matrix.python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install --upgrade setuptools
          python3 -m pip install -r requirements.txt
      - name: Lint with Ruff
        run: ruff check --output-format=github .
        continue-on-error: true
      - name: Run tests
        run: |
          cd app
          make test
